INSERT INTO `singer` VALUES ('tsvdtb3bqmfqwq', 'Afrojack ft Luis Fonsi', 0, '', 'http://chiasenhac.vn/data/face/1/273.jpg');
INSERT INTO `singer` VALUES ('tsvdtb3cqmfqwv', 'R3hab ft VÉRITÉ', 0, '', 'http://chiasenhac.vn/data/face/1/352.jpg');
INSERT INTO `singer` VALUES ('tsvdtbb7qmfqqt', 'Gryffin ft Illenium ft Daya', 0, '', 'http://chiasenhac.vn/data/face/1/686.jpg');
INSERT INTO `singer` VALUES ('tsvdtbbbqmfqqq', 'Lady Gaga', 0, '', 'http://chiasenhac.vn/data/face/1/77.jpg');
INSERT INTO `singer` VALUES ('tsvdtc55qmfvhh', 'Sơn Tùng M-TP', 0, '', 'http://chiasenhac.vn/data/face/1/4.jpg');
INSERT INTO `singer` VALUES ('tsvdtc56qmfvhk', 'Sơn Tùng M-TP', 0, '', 'http://chiasenhac.vn/data/face/1/4.jpg');
INSERT INTO `singer` VALUES ('tsvdtc65qmfvkh', 'Sơn Tùng M-TP', 0, '', 'http://chiasenhac.vn/data/face/1/4.jpg');
INSERT INTO `singer` VALUES ('tsvdtccbqmfvvq', 'Grey-D (Đoàn Thế Lân)', 0, '', '');
INSERT INTO `singer` VALUES ('tsvdtd06qmfmnk', 'Đông Nhi', 0, '', 'http://chiasenhac.vn/data/face/1/65.jpg');
INSERT INTO `singer` VALUES ('tsvdtdmrqmfm8a', 'Linkin Park ft Pusha T ft Stormzy', 0, '', 'http://chiasenhac.vn/data/face/1/106.jpg');
INSERT INTO `singer` VALUES ('tsvdtdwbqmfm9q', 'DNCE ft Nicki Minaj', 0, '', 'http://chiasenhac.vn/data/face/1/525.jpg');
INSERT INTO `singer` VALUES ('tsvdtdz0qmfm1n', 'Đông Nhi', 0, '', 'http://chiasenhac.vn/data/face/1/65.jpg');
INSERT INTO `singer` VALUES ('tsvdtq5cqmfehv', 'Mr Siro', 0, '', 'http://chiasenhac.vn/data/face/1/11.jpg');
INSERT INTO `singer` VALUES ('tsvdtqctqmfevf', 'OnlyC', 0, '', 'http://chiasenhac.vn/data/face/1/18.jpg');
INSERT INTO `singer` VALUES ('tsvdtqvvqmfe22', 'Young Thug ft 2 Chainz ft Wiz Khalifa ft PnB Rock', 0, '', 'http://chiasenhac.vn/data/face/1/704.jpg');
INSERT INTO `singer` VALUES ('tsvdtqvzqmfe21', 'Lil Uzi Vert ft Quavo ft Travis Scott', 0, '', 'http://chiasenhac.vn/data/face/1/707.jpg');
INSERT INTO `singer` VALUES ('tsvdtqz5qmfe1h', 'J Balvin ft Pitbull ft Camila Cabello', 0, '', 'http://chiasenhac.vn/data/face/1/703.jpg');
INSERT INTO `singer` VALUES ('tsvdtrdrqmfama', 'Seven Lions ft Skyler Stonestreet', 0, '', 'http://chiasenhac.vn/data/face/1/706.jpg');
INSERT INTO `singer` VALUES ('tsvdtt7zqmfft1', 'Mai Tiến Dũng', 0, '', '');
INSERT INTO `singer` VALUES ('tsvdtwtzqmf9f1', 'Luis Fonsi ft Daddy Yankee ft Justin Bieber', 0, '', 'http://chiasenhac.vn/data/face/1/681.jpg');
INSERT INTO `singer` VALUES ('tsvq0363qenwkw', 'Trung Quân', 0, '', 'http://chiasenhac.vn/data/face/1/140.jpg');
INSERT INTO `singer` VALUES ('tsvq03rsqenwa4', 'The Chainsmokers ft Emily Warren', 0, '', 'http://chiasenhac.vn/data/face/1/191.jpg');
INSERT INTO `singer` VALUES ('tsvq03srqenw4a', 'Martin Garrix ft Brooks', 0, '', 'http://chiasenhac.vn/data/face/1/402.jpg');
INSERT INTO `singer` VALUES ('tsvq03wdqenw9m', 'The Chainsmokers', 0, '', 'http://chiasenhac.vn/data/face/1/191.jpg');
INSERT INTO `singer` VALUES ('tsvq05wqqenh9e', 'Selena Gomez', 0, '', 'http://chiasenhac.vn/data/face/1/334.jpg');
INSERT INTO `singer` VALUES ('tsvq065zqenkh1', 'Bùi Anh Tuấn ft Ái Phương', 0, '', 'http://chiasenhac.vn/data/face/1/155.jpg');
INSERT INTO `singer` VALUES ('tsvq067qqenkte', 'Chu Bin', 0, '', 'http://chiasenhac.vn/data/face/1/87.jpg');
INSERT INTO `singer` VALUES ('tsvq0c3cqenvwv', 'Đan Nguyên', 0, '', 'http://chiasenhac.vn/data/face/1/9.jpg');
INSERT INTO `singer` VALUES ('tsvq0ccvqenvv2', 'Noo Phước Thịnh', 0, '', 'http://chiasenhac.vn/data/face/1/122.jpg');
INSERT INTO `singer` VALUES ('tsvq0cssqenv44', 'Đan Nguyên ft Như Quỳnh', 0, '', 'http://chiasenhac.vn/data/face/1/9.jpg');
INSERT INTO `singer` VALUES ('tsvq0d5dqenmhm', 'Isaac', 0, '', 'http://chiasenhac.vn/data/face/1/371.jpg');
INSERT INTO `singer` VALUES ('tsvq0rcqqenave', 'The Chainsmokers', 0, '', 'http://chiasenhac.vn/data/face/1/191.jpg');
INSERT INTO `singer` VALUES ('tsvq0rdmqenam8', 'Dương Hồng Loan', 0, '', 'http://chiasenhac.vn/data/face/1/485.jpg');
INSERT INTO `singer` VALUES ('tsvq0vqwqen2e9', 'Harry Styles', 0, '', 'http://chiasenhac.vn/data/face/1/699.jpg');
INSERT INTO `singer` VALUES ('tsvq0zb3qen1qw', 'Hà Anh Tuấn ft Bích Phương', 0, '', 'http://chiasenhac.vn/data/face/1/591.jpg');
INSERT INTO `singer` VALUES ('tsvq0zc6qen1vk', 'Yến Trang', 0, '', '');
INSERT INTO `singer` VALUES ('tsvq0zcsqen1v4', 'Thu Thuỷ', 0, '', 'http://chiasenhac.vn/data/face/1/701.jpg');
INSERT INTO `singer` VALUES ('tsvqv0c0qe2nvn', 'Soobin Hoàng Sơn', 0, '', 'http://chiasenhac.vn/data/face/1/387.jpg');
INSERT INTO `singer` VALUES ('tsvqvm7cqe28tv', 'Tóc Tiên', 0, '', 'http://chiasenhac.vn/data/face/1/377.jpg');
INSERT INTO `singer` VALUES ('tsvqvsbcqe24qv', 'Rhymastic', 0, '', 'http://chiasenhac.vn/data/face/1/530.jpg');
INSERT INTO `singer` VALUES ('tsvqvvqbqe22eq', 'OnlyC ft Lou Hoàng', 0, '', 'http://chiasenhac.vn/data/face/1/18.jpg');
INSERT INTO `singer` VALUES ('tsvqz070qe1ntn', 'Vũ Cát Tường', 0, '', 'http://chiasenhac.vn/data/face/1/266.jpg');
INSERT INTO `singer` VALUES ('tsvqz0c3qe1nvw', 'Rhymastic', 0, '', 'http://chiasenhac.vn/data/face/1/530.jpg');
INSERT INTO `singer` VALUES ('tsvqz6brqe1kqa', 'Clean Bandit ft Zara Larsson', 0, '', 'http://chiasenhac.vn/data/face/1/213.jpg');
INSERT INTO `singer` VALUES ('tsvqz6vqqe1k2e', 'Kai Đinh', 0, '', 'http://chiasenhac.vn/data/face/1/667.jpg');
INSERT INTO `singer` VALUES ('tsvqzmcvqe18v2', 'Soobin Hoàng Sơn', 0, '', 'http://chiasenhac.vn/data/face/1/387.jpg');
INSERT INTO `singer` VALUES ('tsvqzqzmqe1e18', 'Hương Tràm', 0, '', 'http://chiasenhac.vn/data/face/1/284.jpg');
INSERT INTO `singer` VALUES ('tsvqzr53qe1ahw', 'Chi Dân', 0, '', 'http://chiasenhac.vn/data/face/1/239.jpg');
INSERT INTO `singer` VALUES ('tsvqzsb7qe14qt', 'G-Eazy ft Kehlani', 0, '', 'http://chiasenhac.vn/data/face/1/693.jpg');
INSERT INTO `singer` VALUES ('tsvqzvz3qe121w', 'Tiên Tiên', 0, '', 'http://chiasenhac.vn/data/face/1/382.jpg');
